#define TOTAL_TUNING_PARTS 14
#define MAX_TUNING_PARTS_COMPONENTS 20

enum PLAYER_TUNING_MENU_Info
{
	tuning_menu_NAME[24],
	tuning_menu_ID,
	tuning_menu_PIECES
};
new PLAYER_TUNING_MENU[MAX_PLAYERS][MAX_TUNING_PARTS_COMPONENTS][PLAYER_TUNING_MENU_Info];