enum {
	ELECTRONIC_BOOMBOX,
	ELECTRONIC_MP3
};

enum E_ELECTRONICS_DATA {
	ep_TYPE,
	ep_NAME[24],
	ep_PRICE
};
new ELECTRONIC_PRODUCTS[][E_ELECTRONICS_DATA] = {
	{ ELECTRONIC_MP3, "Reproductor MP3", 500 },
	{ ELECTRONIC_BOOMBOX, "Parlantes", 1750 }
};